### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by DavidParks8** [DavidParks8/Owin-Authorization#3]
@brockallen can I please get a code review?  As far as I can tell, the only things the library is missing are unit tests and nuspec files.  I was planning on turning it into three different nuget packages.  One for the common classes, one for mvc, and one for web api.

**Comment by brockallen** [comment]
I'll try to take a look when I can. I'm traveling this week.

**Comment by DavidParks8** [comment]
Thanks. Whenever you have some free time, I would really appreciate it.

**Comment by brockallen** [comment]
We can also ask @leastprivilege to look (since i'm swamped)

**Comment by DavidParks8** [comment]
@brockallen I'm feeling fairly confident in the stability and architecture of the project.  I think it's time for a blog post to increase visibility and get some feedback.  Would you mind making one?

**Comment by brockallen** [comment]
Hey -- Still swamped as usual. One thing to consider -- they've RTM'd the authorization bits -- have you updated to match those?

**Comment by DavidParks8** [comment]
I have not, but none of the changes alter functionality.  They're mostly doc comment additions.  I'll make a few issues to cover them.

**Comment by brockallen** [comment]
Well I know some APIs and classes changed names at least.

**Comment by DavidParks8** [comment]
Those classes would be the `AuthorizationContext` which changed to `AuthorizationHandlerContext` and some very minor `AuthorizationHandler<TReq>` changes which will be covered by [#43](https://github.com/DavidParks8/Owin-Authorization/issues/43).  What I meant by "alter functionality" was that no major core authorization logic was changed.  The changes for [#841](https://github.com/aspnet/Security/issues/841) have already been synced to this repo.

**Comment by DavidParks8** [comment]
While review is always welcome, it is probably not as necessary as it was early on because this library has been used by many people in production environments without complaint for a few months.  If anyone likes, I would be happy to reopen this ticket.
