### ISSUE TITLE
Controller\View Based Authorization

### ISSUE THREAD

**Issue by JamesItSolutionsLtd** [DavidParks8/Owin-Authorization#53]
Hello 

does this solution also handle View Based Authorization
as detailed here : https://docs.microsoft.com/en-us/aspnet/core/security/authorization/views

or in our case calling the AuthorizationService from within the controller

**Comment by DavidParks8** [comment]
It absolutely does.  This solution strives to be as close to the .NET core version as possible.  If you can get an `IAuthorizationService` instance into your controller, then you can use it in any way you'd like.  If you use a dependency injection framework such as autofac, then you could do something like the following to register: 
```cs
builder.RegisterType<DefaultAuthorizationPolicyProvider>()
    .As<IAuthorizationPolicyProvider>();
builder.Register(resolver => new DefaultAuthorizationService(
        resolver.Resolve<IAuthorizationPolicyProvider>(),
        new[] {new PassThroughAuthorizationHandler()}))
    .As<IAuthorizationService>();
```

If you don't use dependency injection, then you could create an instance in your controller.  An easy way to do so which uses many default implementations would be:
```cs
var authorizationService = AuthorizationDependencies.Create(new AuthorizationOptions()).Service;
```

**Comment by JamesItSolutionsLtd** [comment]
Thanks for the help.

**Comment by JamesItSolutionsLtd** [comment]
we are using Unity as our DI (yes i know)

im struggling to pass in the AuthorizationOptions to the DefaultAuthorizationPolicyProvider
I've tried to follow your AutoFac sample.

i have got the following in startup.cs

`app.UseAuthorization(options =>
            {
                options.AddPolicy("TEMP", policy => { policy.RequireRole("TEMP"); });
                options.Dependencies = new UnityAuthorizationDependencies(UnityConfig.GetConfiguredContainer());            
            });
`

But it appears that just setting dependencies doesn't pass the AuthorizationOptions to the PolicyProvider

so im getting Policy Name not found error.

**Comment by DavidParks8** [comment]
My apologies for forgetting to mention this, but when doing dependency injection, you also need to register the instance of your `AuthorizationOptions` with which you set your policies.

```cs
var options = new AuthorizationOptions();
options.AddPolicy("TEMP", policy =>
{
    policy.RequireRole("TEMP"); 
});
// further down the page with autofac or your preferred IoC framework
builder.Register(resolver => options).As<AuthorizationOptions>();
// further down the page after you've set options.Dependencies to your unity version
app.UseAuthorization(options);
```

There is a working autofac sample startup file [here](https://github.com/DavidParks8/Owin-Authorization/blob/master/samples/WebApi%20Autofac/Startup.cs) which may help.

**Comment by JamesItSolutionsLtd** [comment]
Perfect just what i was missing.
for anyone else using unity here is my container setup code

```
var options = new AuthorizationOptions();

options.AddPolicy("Client.Admin", policy => { policy.Requirements.Add(new PermissionsRequirement("Client.Admin")); });


var container = UnityConfig.GetConfiguredContainer();

container.RegisterInstance(options, new ContainerControlledLifetimeManager());

container.RegisterType<IAuthorizationPolicyProvider, DefaultAuthorizationPolicyProvider>(new ContainerControlledLifetimeManager(),
                new InjectionConstructor(
                    new InjectionParameter<AuthorizationOptions>(container.Resolve<AuthorizationOptions>())
                    ));

container.RegisterInstance<IEnumerable<IAuthorizationHandler>>(
                new IAuthorizationHandler[]
                {
                    new PermissionsAuthorizationHandler(container.Resolve<IAuthorizationBusinessService>())
                },
                new ContainerControlledLifetimeManager());

container.RegisterInstance<IAuthorizationService>(
                new DefaultAuthorizationService(container.Resolve<IAuthorizationPolicyProvider>(), container.Resolve<IEnumerable<IAuthorizationHandler>>()),
                new ContainerControlledLifetimeManager()
            );

options.Dependencies = new UnityAuthorizationDependencies(container); 

app.UseAuthorization(options);
```
