### ISSUE TITLE
Fix results for ContentController.Get() (root) so that it works for users with non-root access

### ISSUE THREAD

**Issue by Shazwazza** [DavidParks8/Owin-Authorization#55]
The result of this should return the root of what a user has access too

**Comment by DavidParks8** [comment]
I need a bit more to understand exactly what you are referring to. Could you please provide an example to help me understand?

**Comment by Shazwazza** [comment]
Wow how embarrassing... I created an issue on the wrong tracker for an entirely different project. Lol sorry! 😆
